#!/bin/bash

# Update and Install
sudo pacman -Syyu
sudo pacman -S fish \
  kitty \
  neovim \
  wget \
  git \
  xclip \
  ranger \
  ripgrep \
  tmux \
  eza \
  zathura \
  zathura-pdf-poppler

# AUR yay
yay -S pfetch

# Install
CONF=$HOME/.config
mkdir copy

if [ -d $CONF/fish ]; then
  mv $CONF/fish copy/fish
fi

if [ -d kitty ]; then
  mv $CONF/kitty copy/kitty
fi

if [ -d $CONF/nvim ]; then
  mv $CONF/nvim copy/nvim
fi

if [ -d $CONF/tmux ]; then
  mkdir copy/tmux
  mv $CONF/tmux/tmux.conf copy/tmux
fi

cp -r fish $CONF
cp -r kitty $CONF
cp -r tmux $CONF

# Install NvChad
rm -rf $HOME/.local/share/nvim
rm -rf $HOME/.config/nvim
mkdir $HOME/.config/nvim
git clone https://github.com/NvChad/NvChad --depth 1
mv NvChad/* $CONF/nvim/ && nvim
mkdir $CONF/nvim/lua
cp -r nvim/custom $CONF/nvim/lua/ && nvim

# Install TMUX
mkdir $CONF/tmux
git clone https://github.com/tmux-plugins/tpm $CONF/tmux/

# Completed
echo "--> Installation completed"
echo "--> run TMUX for plugins"
